const express = require('express');
const router = express.Router();
const usersController = require('../controllers/users_controller');
const postController = require('../controllers/post_controller');
router.get('/profile', usersController.profile);
router.get('/post', postController.post);
router.get('/sign-in', usersController.signin);
router.get('/sign-up', usersController.signup);
router.post('/create', usersController.create);
router.post('/create-session', usersController.createSession);
router.post('/signOut', usersController.signOut);
module.exports = router;